apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels: { app: evaluation-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: evaluation-service } }
  template:
    metadata:
      labels: { app: evaluation-service }
    spec:
      containers:
        - name: evaluation-service
          image: 436964578473.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service:v1.0.0-INITIAL
          ports: [{ containerPort: 8004 }]
          env:
            - name: PORT
              value: "8004"
            - name: REDIS_URL
              valueFrom: { secretKeyRef: { name: evaluation-secrets, key: redis_addr } }
            - name: AWS_SQS_URL
              valueFrom: { secretKeyRef: { name: evaluation-secrets, key: sqs_queue_url } }
            - name: AWS_REGION
              value: "us-east-1"
            - name: FLAG_SERVICE_URL
              value: "http://flag-service.togglemaster.svc.cluster.local"
            - name: TARGETING_SERVICE_URL
              value: "http://targeting-service.togglemaster.svc.cluster.local"
            - name: SERVICE_API_KEY
              valueFrom: { secretKeyRef: { name: evaluation-secrets, key: service_api_key } }
            # --- OpenTelemetry ---
            - name: OTEL_SERVICE_NAME
              value: "evaluation-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=togglemaster,deployment.environment=hml"
          readinessProbe:
            httpGet: { path: /health, port: 8004 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8004 }
            initialDelaySeconds: 15
          resources:
            requests: { cpu: 50m,  memory: 64Mi }
            limits:   { cpu: 250m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  selector: { app: evaluation-service }
  ports: [{ port: 80, targetPort: 8004 }]
