apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels: { app: analytics-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: analytics-service } }
  template:
    metadata:
      labels: { app: analytics-service }
    spec:
      containers:
        - name: analytics-service
          image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service:v1.0.0-c8aef1a
          ports: [{ containerPort: 8005 }]
          env:
            - name: PORT
              value: "8005"
            - name: DYNAMODB_TABLE
              value: "ToggleMasterAnalytics"
            - name: SQS_QUEUE_URL
              valueFrom: { secretKeyRef: { name: analytics-secrets, key: sqs_queue_url } }
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            requests: { cpu: 50m,  memory: 64Mi }
            limits:   { cpu: 250m, memory: 256Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  selector: { app: analytics-service }
  ports: [{ port: 80, targetPort: 8005 }]
